cjstmdgusqw/moyeoYoung_backend

- moyoung/build.gradle
- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/RoomFeedDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/BaseTimeEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/repository/RoomfeedRepository.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedService.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/repository/OpenRoomRepository.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomService.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
- moyoung/src/main/resources/application.properties
FEAT : Roomfeed.Controller (진행중)
> FEAT : Roomfeed.Controller (진행중)

- moyoung/src/main/java/com/kosta/moyoung/member/controller/AuthController.java
- moyoung/src/main/java/com/kosta/moyoung/member/controller/MemberController.java
- moyoung/src/main/java/com/kosta/moyoung/member/entity/Member.java
- moyoung/src/main/java/com/kosta/moyoung/member/repository/MemberRepository.java
- moyoung/src/main/java/com/kosta/moyoung/member/service/AuthService.java
- moyoung/src/main/java/com/kosta/moyoung/member/service/CustomMemberService.java
- moyoung/src/main/java/com/kosta/moyoung/member/util/UserPrincipal.java
- moyoung/src/main/java/com/kosta/moyoung/security/SecurityConfig.java
- moyoung/src/main/java/com/kosta/moyoung/security/jwt/JwtFilter.java
FEAT: Member Entity 및 UserPrincipal 수정
Member: userId -> memberId로 변경
UserPrincipal  : 
private Member member; 추가
getUsername() -> member.getEmail();
> FEAT: Member Entity 및 UserPrincipal 수정

- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/RoomFeedDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/PhotoEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/repository/PhotoRepository.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedService.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/security/SecurityConfig.java
- moyoung/src/main/resources/application.properties
FEAT : RoomfeedController writefeed
> FEAT : RoomfeedController writefeed

- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/RoomFeedDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/repository/RoomfeedRepository.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedService.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/oauth2/service/CustomDefaultOAuth2UserService.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/resources/application.properties
FEAT : 'detailroomfeed 디테일 피드 구현'
> FEAT : 'detailroomfeed 디테일 피드 구현'

- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/repository/RoomfeedRepository.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
Fix : RoomfeedController.jsx 피드 조회 변경
file쪽에 오류가 있어서 수정
> Fix : RoomfeedController.jsx 피드 조회 변경

- moyoung/src/main/java/com/kosta/moyoung/youthspace/controller/YouthSpaceController.java
- moyoung/src/main/java/com/kosta/moyoung/youthspace/repository/YouthSpaceRepository.java
- moyoung/src/main/java/com/kosta/moyoung/youthspace/service/YouthSpaceService.java
- moyoung/src/main/java/com/kosta/moyoung/youthspace/service/YouthSpaceServiceImpl.java
> FEAT:YouthSpace

- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/repository/RoomfeedRepository.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedService.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/entity/Room.java
FIX : RoomFeedController.java Service등 고침
> FIX : RoomFeedController.java Service등 고침

- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomService.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/util/FileService.java
- moyoung/src/main/java/com/kosta/moyoung/util/FileServiceImpl.java
파일 저장하는거랑 화면에출력하는메소드 두개 util패키지 > fileService 로 따로 뺐음
> FEAT:FileService,  FileServiceImpl

- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedService.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
> 'FEAT : modifyfeed 수정기능 완료'

- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomService.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
> FIX:OpenRoomService

- moyoung/src/main/java/com/kosta/moyoung/youthspace/controller/YouthSpaceController.java
- moyoung/src/main/java/com/kosta/moyoung/youthspace/service/YouthSpaceService.java
- moyoung/src/main/java/com/kosta/moyoung/youthspace/service/YouthSpaceServiceImpl.java
> FIX:YouthSpaceController,YouthSpaceService

- moyoung/src/main/java/com/kosta/moyoung/member/dto/MemberResponseDto.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
메잌룸, 북마크 관련 로그인된 멤버id받아와서 연결시키기 완
> FIX:MemberResponseDto, OpenRoomControoller, OpenRoomService

- moyoung/src/main/resources/application.properties
- moyoung/src/test/java/com/kosta/moyoung/MoyoungApplicationTests.java
FIX : "application proferties" 본인 네이버 이메일이랑 비밀번호적용하기
> FIX : "application proferties"

- moyoung/src/main/java/com/kosta/moyoung/member/entity/Member.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/dto/RoomDTO.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/entity/Room.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/security/CorsConfig.java
- moyoung/src/main/resources/application.properties
> FIX:OpenRoomServiceImpl, Member, Room, RoomDTO

- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/CommentDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/LikeDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/RoomFeedDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/CommentEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/LikeEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/repository/CommentRepository.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/repository/LikeRepository.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/CommentService.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/CommentServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedService.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/member/controller/MemberController.java
- moyoung/src/main/java/com/kosta/moyoung/member/entity/Member.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/security/CorsConfig.java
FEAT : Like.Entity생성 및 좋아요 기능 완료
Comment.Entity도 생성하였고 댓글 기능 구현중
> FEAT : Like.Entity생성 및 좋아요 기능 완료

- moyoung/src/main/java/com/kosta/moyoung/member/service/MemberService.java
- moyoung/src/main/java/com/kosta/moyoung/member/service/MemberServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/entity/Room.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
> FIX:Room, OpenRoomServiceImpl

- moyoung/src/main/java/com/kosta/moyoung/security/CorsConfig.java
> Feat. rooms corseconfig

- moyoung/src/main/java/com/kosta/moyoung/feedroom/controller/RoomFeedController.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/CommentDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/dto/RoomFeedDTO.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/CommentEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/LikeEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/CommentService.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/CommentServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/member/controller/AuthController.java
- moyoung/src/main/java/com/kosta/moyoung/member/entity/Member.java
- moyoung/src/main/resources/application.properties
FEAT : commentCOntroller 댓글 작성 및 삭제 완료, 좋아요 로직 완성
> FEAT : commentCOntroller 댓글 작성 및 삭제 완료, 좋아요 로직 완성

- moyoung/build.gradle
- moyoung/src/main/java/com/kosta/chat/config/WebSocketConfiguration.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/roomChat/config/RoomChatWebSocketConfiguration.java
- moyoung/src/main/java/com/kosta/moyoung/roomChat/service/WebSocketService.java
- moyoung/src/main/java/com/kosta/moyoung/security/CorsConfig.java
- moyoung/src/main/java/com/kosta/moyoung/security/SecurityConfig.java
> FEAT : Chat.jsx 채팅기능 구현 완료

- moyoung/src/main/resources/application.properties
DOCS: application.properties 보안 수정
> DOCS: application.properties 보안 수정

- moyoung/src/main/java/com/kosta/moyoung/member/controller/MemberController.java
- moyoung/src/main/java/com/kosta/moyoung/member/repository/MemberRepository.java
- moyoung/src/main/java/com/kosta/moyoung/member/service/MemberService.java
- moyoung/src/main/java/com/kosta/moyoung/member/service/MemberServiceImpl.java
- moyoung/src/main/resources/application.properties
FEAT: memberController memberProfile 구현
> FEAT: memberProfile

- moyoung/src/main/java/com/kosta/moyoung/notice/controller/NoticeController.java
- moyoung/src/main/java/com/kosta/moyoung/security/CorsConfig.java
- moyoung/src/main/java/com/kosta/moyoung/todo/controller/TodoController.java
- moyoung/src/main/java/com/kosta/moyoung/todo/entity/Todo.java
- moyoung/src/main/java/com/kosta/moyoung/todo/repository/TodoRepository.java
> Feat. Notice, Todo

- moyoung/src/main/java/com/kosta/moyoung/member/controller/MemberController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/OpenRoomController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/entity/Room.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomService.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/OpenRoomServiceImpl.java
> FEAT:OpenRoomService,OpenRoomController

- moyoung/src/main/java/com/kosta/moyoung/notice/entity/Notice.java
> Fix. Notice content DB Type

- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/member/entity/Member.java
- moyoung/src/main/resources/application.properties
FIX : Myfeed 오류로 인해서 Entitiy수정
> FIX : Myfeed 오류로 인해서 Entitiy수정

- moyoung/src/main/java/com/kosta/moyoung/member/controller/MemberController.java
- moyoung/src/main/java/com/kosta/moyoung/util/FileServiceImpl.java
> Feat. Add Mac Compatibility

- moyoung/src/main/resources/application.properties
> Fix. BASE URL

- moyoung/src/main/java/com/kosta/moyoung/config/WebConfig.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/entity/RoomfeedEntity.java
- moyoung/src/main/java/com/kosta/moyoung/feedroom/service/RoomfeedServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/notice/controller/NoticeController.java
- moyoung/src/main/java/com/kosta/moyoung/security/CorsConfig.java
- moyoung/src/main/java/com/kosta/moyoung/security/LoginFailureHandler.java
- moyoung/src/main/java/com/kosta/moyoung/security/LoginSuccessHandler.java
- moyoung/src/main/java/com/kosta/moyoung/todo/controller/TodoController.java
- moyoung/src/main/resources/application.properties
> Fix. BASE URL Setting

- moyoung/src/main/java/com/kosta/moyoung/member/controller/MemberController.java
- moyoung/src/main/java/com/kosta/moyoung/member/dto/MemberResponseDto.java
- moyoung/src/main/java/com/kosta/moyoung/member/service/MemberService.java
- moyoung/src/main/java/com/kosta/moyoung/member/service/MemberServiceImpl.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/controller/EnteranceController.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/dto/EnteranceDTO.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/entity/Enterance.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/repository/EnteranceRepository.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/EnteranceService.java
- moyoung/src/main/java/com/kosta/moyoung/openroom/service/EnteranceServiceImpl.java
비공개방 가입시 방장수락/거절 기능 추가, 
마이페이지에서 방장일 때 내가만든방, 가입한 방 둘 다 뜨는 오류 수정!
마이페이지에서 가입/대기중 목록 조회 기능 추가 완!
> FEAT:EnteranceService ,MemberSerivice
